### ISSUE TITLE
imagemin-jpeg-recompress returns Error when compressing

### ISSUE THREAD

**Issue by marocas** [imagemin/imagemin-jpeg-recompress#11]
´´´´
$ npm install imagemin-jpeg-recompress
npm WARN package.json BY_Mailer@0.0.1 No repository field.
|

> jpeg-recompress-bin@2.0.2 postinstall C:\sites_testes\node_modules\imagemin-j
> peg-recompress\node_modules\jpeg-recompress-bin
> node lib/install.js

  √ jpeg-recompress pre-build test passed successfully

imagemin-jpeg-recompress@4.0.0 node_modules\imagemin-jpeg-recompress
├── is-jpg@1.0.0
├── through2@0.6.3 (xtend@4.0.0, readable-stream@1.0.33)
└── jpeg-recompress-bin@2.0.2 (logalot@2.0.0, bin-wrapper@2.1.1)

C:>grunt imagemin
Running "imagemin:main" (imagemin) task
Warning: Error: Premature end of JPEG file
Bogus Huffman table definition
 in file _images/mee.jpg Use --force to continue.

Aborted due to warnings.
´´´´

my task config is this:

´´´´
var imageCompressEngine = require('imagemin-jpeg-recompress');

  var globalConfig = {

```
imagemin: {
  main: {
    options: {
      optimizationLevel: 7,
      pngquant: true,
      progressive: true,
      use: [imageCompressEngine()]
    },
    files: [
      {
        expand: true,
        cwd: '<%= cfg.root %><%= cfg.src.images %>',
        src: ['**/*.{png,jpg,jpeg,gif,ico}'],
        dest: '<%= cfg.root %><%= cfg.dest.images %>'
      }
    ]
  }
},
```

});
´´´´
My dependences are the latest versions of 
  "grunt-contrib-imagemin": "^0.9.2", and "imagemin-jpeg-recompress": "^4.0.0".

I'm working on windows OS, if i use another plugin, like imagemin-mozjpeg, it works perfectly.
I want to use this plugin, because it as a better compression.

Best regards, Mário Silva

**Comment by dwest100** [comment]
Hi,
What does “terminated by signal 11” mean in the screen output?
