### ISSUE TITLE
Premature end of JPEG file (Gulp)

### ISSUE THREAD

**Issue by Landen13** [imagemin/imagemin-jpeg-recompress#12]
I'm trying to recompress jpeg after saving via Photoshop (Save As)

```
var jpegRecompress = require('imagemin-jpeg-recompress');

gulp.task('jpg', function () {
    gulp.src('./images/temp/*.jpg')
        .pipe(jpegRecompress({loops: 3})())
        .pipe(gulp.dest('./images/'));
});
```

error:
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Premature end of JPEG file
JPEG datastream contains no image

    at ChildProcess.<anonymous> (D:\projects\gulp-it\node_modules\imagemin-jpeg-recompress\index.js:100:8)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)
```

When I'm tring to recompress jpeg, saved via Save For Web in Photoshop:

error:
```
Error: Premature end of JPEG file
Bogus DQT index 9
```

Any suggestions?

**Comment by shinnn** [comment]
Seems to be an issue with [jpeg-recompress](https://github.com/danielgtaylor/jpeg-archive#jpeg-recompress) binary. Please open a new issue on [jpeg-archive](https://github.com/danielgtaylor/jpeg-archive/issues) repository instead.

Thanks for reporting.

**Comment by Landen13** [comment]
Are you sure?
Just checked jpeg-recompress.exe from their jpeg-archive
everything is ok
same images - no errors

**Comment by shinnn** [comment]
Probably you checked it with [v2.1.0](https://github.com/danielgtaylor/jpeg-archive/releases/tag/2.1.0) binary? This plugin uses v2.0.0 binary.

> Are you sure?

Sure. It was really better to report this on jpeg-archive repo.

**Comment by shinnn** [comment]
[Released imagemin-jpeg-recompress v4.2.0](https://github.com/imagemin/imagemin-jpeg-recompress/commit/a41b4f63a997d06292fc6ace923877367b15d2e6) which uses jpeg-recompress v2.1.0.

**Comment by Landen13** [comment]
Yeah, thanks, but the problem still exists

**Comment by shinnn** [comment]
The cause is really [this image](http://impressivesound.net/01.jpg)?

I cannot reproduce the error you're running into even if I use the same script as you commented [here](https://github.com/imagemin/imagemin-jpeg-recompress/issues/12#issue-67636624).

**Comment by Landen13** [comment]
Hmmm... that's interesting.

Yes, this image. And the same script.

My package.json:
```
  "devDependencies": {
    "gulp": "^3.8.11",
    "imagemin-jpeg-recompress": "^4.2.0"
  },
  "engines": {
    "node": "=>0.10.22"
  }
```

My gulpfile.js:
```
var gulp = require('gulp'),
var imageminJpegRecompress = require('imagemin-jpeg-recompress');

gulp.task('jpg', function () {
	return gulp.src('images/temp/*.jpg')
		.pipe(imageminJpegRecompress({loops: 3})())
		.pipe(gulp.dest('images/build/'));
});
```

LOG:
```
Running 'jpg'...
[12:18:27] Using gulpfile D:\projects\gulp-it\gulpfile.js
[12:18:27] Starting 'jpg'...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Premature end of JPEG file
JPEG datastream contains no image

    at ChildProcess.<anonymous> (D:\projects\gulp-it\node_modules\imagemin-jpeg-recompress\index.js:101:11)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)
```

**Comment by shinnn** [comment]
@Landen13 Can you use jpeg-recompress binary with stdin/out ?

(On POSIX)

```
cat 01.jpg | jpeg-recompress - - > test.jpg
```

**Comment by drazik** [comment]
Hi,

we have the same error here with Windows 7 pro 64 bits. We are using the plugin with Gulp. Here is our task : 

```javascript
gulp.task('images', function(){
    gulp.src(taskConfig.src)
        .pipe(imageminJpegRecompress({loops: 3, method: 'smallfry'})())
        .pipe(gulp.dest(taskConfig.dest));
});
```

We are using the 4.2.0 version.

A teammate tested with the same task and same plugin version on MacOS, he doesn't have any error. It seems the problem only appears on Windows. Have you any idea ?

@Landen13 , do you use Windows ?

**Comment by Landen13** [comment]
Windows 7 x64

**Comment by drazik** [comment]
So I think the problem is closely related to Windows. @shinnn do you have any idea to fix it ?

**Comment by shinnn** [comment]
Thanks for your detailed report, @drazik.

> @shinnn do you have any idea to fix it ?

As I said [here](https://github.com/imagemin/imagemin-jpeg-recompress/issues/12#issuecomment-91632748), it should be fixed in [the upstream project](https://github.com/danielgtaylor/jpeg-archive#jpeg-recompress). We don't want to include monkey-patching code in our project.

However, if https://github.com/imagemin/imagemin-jpeg-recompress/issues/12#issuecomment-93419590 isn't fixed for a while and so many Windows users suffer from this problem, I'll consider monky-patching.

**Comment by drazik** [comment]
Yep @shinnn you're right. Thank you. I think there is a lot of people that encounter the same issue but don't come here to say it! If you can do a quick monkey-patch, it would be great :)

**Comment by Landen13** [comment]
Yeah, it would be great. There is only this plugin left to configure in my gulpfile, so I hope that issue would be fixed soon.
drazik, thnx for your help!

**Comment by shinnn** [comment]
OK, I can't start to fix it right now but I'll update this plugin within 24 hours :)

Does this command work fine on Windows?

```sh
# Read from a file (not stdin) but output to stdout
jpeg-recompress 01.jpg - > test.jpg
```

**Comment by Landen13** [comment]
```
jpeg-recompress 01.jpg - > test.jpg
Metadata size is 21kb
ssim at q=67 (40 - 95): 0.997217
ssim at q=81 (68 - 95): 0.998685
ssim at q=88 (82 - 95): 0.999433
ssim at q=92 (89 - 95): 0.999759
ssim at q=94 (93 - 95): 0.999848
Final optimized ssim at q=95: 0.999810
New size is 60% of original (saved 35 kb)
```

**Comment by shinnn** [comment]
Is produced `test.jpg` is a valid image file?

**Comment by Landen13** [comment]
Image file is invalid, even Photoshop can't parse and open it.

**Comment by shinnn** [comment]
Is this OK?

```
jpeg-recompress -s 01.jpg test.jpg
```

**Comment by Landen13** [comment]
Yes. 

```
ssim at q=67 (40 - 95): 0.997217
ssim at q=81 (68 - 95): 0.998685
ssim at q=88 (82 - 95): 0.999433
ssim at q=92 (89 - 95): 0.999759
ssim at q=94 (93 - 95): 0.999848
Final optimized ssim at q=95: 0.999810
New size is 36% of original (saved 56 kb)
```

Image file is valid.

**Comment by shinnn** [comment]
OK I found how to write monkey patch. Wait for a new release.

**Comment by Landen13** [comment]
Thanks a lot!
What this parameter does?

**Comment by shinnn** [comment]
`-s` isn't related to this problem. it just strips metadata from images.

**Comment by Landen13** [comment]
Oh, that's great, I need this option.

**Comment by shinnn** [comment]
imagemin-jpeg-recompress enables it by default. https://github.com/imagemin/imagemin-jpeg-recompress/blob/d50e7ab986e826e6602dfef2e6a9eecf91255756/index.js#L27

**Comment by drazik** [comment]
Great ! I'm waiting for the patch impatiently. Thank you for the work man.

**Comment by shinnn** [comment]
@drazik Check this on your Windows, please. https://github.com/danielgtaylor/jpeg-archive/issues/14#issuecomment-93536701

**Comment by shinnn** [comment]
The upstream project was fixed, so I'll update [the binary wrapper](https://github.com/imagemin/jpeg-recompress-bin) instead of monky-patching.

**Comment by drazik** [comment]
@shinnn I tested the upstream project fix with `cat 01.jpg | jpeg-recompress - - > test.jpg` and it worked very well.

**Comment by shinnn** [comment]
https://github.com/imagemin/imagemin-jpeg-recompress/issues/12#issuecomment-93551421

> after the new release of jpeg-archive

Contact the author of jpeg-archive for the new release.

**Comment by Landen13** [comment]
@shinnn, Daniel has just released the new version of the upstream project (2.1.1), so now you can update jpeg-recompress.

**Comment by shinnn** [comment]
Fixed. Use imagemin-jpeg-recompress v4.2.1.

**Comment by drazik** [comment]
Thanks a lot !
