### ISSUE TITLE
Unable to process images, getting the error "Error: write EPIPE"

### ISSUE THREAD

**Issue by josh18** [imagemin/imagemin-jpeg-recompress#13]
Error that I get
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at WriteWrap.afterWrite (net.js:775:14)
```
My code
```js
return gulp.src('src/img/*.jpg')
        .pipe(imageminJpegRecompress({loops: 3})())
        .pipe(gulp.dest('dist/img'));
```
Let me know if you need any more info from me.

**Comment by shinnn** [comment]
Can you show us the image that can reproduce the error?

**Comment by josh18** [comment]
Just tried it with [this image](http://oyster.ignimgs.com/wordpress/stg.ign.com/2013/10/Batman_102813_1600.jpg) (seems to be happening with all images).

My code
```js
gulp.task('images', function() {
    return gulp.src('test/batman.jpg')
        .pipe(imageminJpegRecompress({loops: 3})())
        .pipe(gulp.dest('test2'));
});
```
I run `gulp images` and the error message above. If if remove `.pipe(imageminJpegRecompress({loops: 3})())` everything works correctly.

**Comment by shinnn** [comment]
I cannot reproduce the error on my machine. My environment is:

```
$ system_profiler SPSoftwareDataType
    System Software Overview:

      System Version: OS X 10.10.3 (******)
      Kernel Version: Darwin 14.3.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: *******
      User Name: ********
      Secure Virtual Memory: Enabled
      Time since boot: 22 days 7:22
$ node -v
v2.3.1
$ npm -v
2.11.2
```

**Comment by josh18** [comment]
I'm on node v0.12.5 (I assume from the high version number you are using io.js?). Also I'm unfortunately on OS X 10.7.5 if that makes a difference?

**Comment by shinnn** [comment]
> you are using io.js?

Yes. I also ran the script with Node v0.12.2 but no error occurred.

Can you install the latest imagemin-jpeg-recompress (v4.3.0) and try again?

**Comment by josh18** [comment]
Just ran npm update and got the error
```
  ✖ Error: The `***/node_modules/imagemin-jpeg-recompress/node_modules/jpeg-recompress-bin/vendor/jpeg-recompress` binary doesn't seem to work correctly
    at BinWrapper.<anonymous> (***/node_modules/imagemin-jpeg-recompress/node_modules/jpeg-recompress-bin/node_modules/bin-wrapper/index.js:156:7)
    at ChildProcess.<anonymous> (***/node_modules/imagemin-jpeg-recompress/node_modules/jpeg-recompress-bin/node_modules/bin-wrapper/node_modules/bin-check/index.js:26:4)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
imagemin-jpeg-recompress@4.3.0 node_modules/imagemin-jpeg-recompress
```

**Comment by shinnn** [comment]
Interesting. The only difference between the previous version and the current version is [through2](https://github.com/rvagg/through2) version.

https://github.com/imagemin/imagemin-jpeg-recompress/compare/v4.2.1...v4.3.0

**Comment by josh18** [comment]
I'm guessing the issue is with `jpeg-recompress-bin` then?

**Comment by shinnn** [comment]
No. I still think there's something wrong with your environment.

**Comment by shinnn** [comment]
@josh18 What is your npm version?

**Comment by josh18** [comment]
Node: v0.12.5
NPM: v2.11.2
OS X: 10.7.5 (maybe that's the issue?)

Still getting the `binary doesn't seem to work correctly` as above when I try to install `imagemin-jpeg-recompress`.

**Comment by shinnn** [comment]
@josh18 Can you run the jpeg-recompress binary directly and check if it works correctly? It's under `YOUR_PROJECT/node_modules/imagemin-jpeg-recompress/node_modules/jpeg-recompress-bin/vendor/jpeg-recompress`.

**Comment by shinnn** [comment]
No feedback.

**Comment by Songworks** [comment]
Got the same issue: Binary is not executable.
For me it is because the binary is 64bit while I am on a 32bit system...

OP might have had the same?

**Comment by shinnn** [comment]
@Songworks https://github.com/imagemin/imagemin-jpeg-recompress/issues/13#issuecomment-118179173

**Comment by Songworks** [comment]
$ jpeg-recompress
bash: jpeg-recompress: cannot execute binary file: Exec format error

If it helps any:
$ file jpeg-recompress 
jpeg-recompress: ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=6fe1a43ed9bf9ace7ff3b95d2e0c3d8ab98ef3d8, not stripped

$ uname -a
Linux laptop-stefan 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:44:48 UTC 2015 i686 i686 i686 GNU/Linux

**Comment by shinnn** [comment]
OK, thanks.

I'm unwilling to biuld 32bit Linux binary and include it to this repository by ourselves. Could you open 
a new issue on https://github.com/danielgtaylor/jpeg-archive/issues and ask the author to add 32bit binary to [the official archive release page](https://github.com/danielgtaylor/jpeg-archive/releases)?

**Comment by Songworks** [comment]
Was about to do that, but apparently they already consider doing a 32bit built:
https://github.com/danielgtaylor/jpeg-archive/issues/29#issuecomment-131106848

So I'll see how it turns out.
Cheers for the quick replies!
