### ISSUE TITLE
CMYK support

### ISSUE THREAD

**Issue by stefanscript** [imagemin/imagemin-jpeg-recompress#17]
Hi, 

Great job with this plugin. Just wandering if there is support for CMYK jpgs. I get an error : Unsupported color conversion request

Cheers

**Comment by kevva** [comment]
Could you give me an example image to test with?

**Comment by TomTasche** [comment]
there you go: 
![feta-pfanne-kreta_preview](https://cloud.githubusercontent.com/assets/128734/19679451/0eb3fafa-9aa2-11e6-9213-0d9bf9a5531e.jpg)

same error occurs for me (using grunt-contrib-imagemin@1.0.0, imagemin-jpeg-recompress@4.3.0 with options accurate: true, quality: "high")

**Comment by t6nand** [comment]
Hi, Facing same issue with CMYK images. Any update?

**Comment by andreypelykh** [comment]
Yes, I have the same issue.

**Comment by sindresorhus** [comment]
Open an issue on the actual binary we use: https://github.com/danielgtaylor/jpeg-archive

Not much we can do about it here.
